### ISSUE TITLE
v0.0.1 - PoC

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-broker-server-extension#1]
# PoC
### Goal

The goal is to provide a first MDS Broker with a most minimal effort, proving that the concept is implementable. 

### Processes

- User 
  - Simple clean page (no other functionalities than Cataloging)
  - Discovery
    - Get overview over assets
    - Show details of an asset
- System
  - Register Connector
  - Unregister Connector
  - Add, update, remove asset

### Architecture
  - [x] Broker-server EDC extension SHALL be implemented in a private repository
  - [x] Broker-server EDC extension MUST be based on sovity's EDC CE
  - [x] Implementation of UI SHALL be done in edc-ui OS repository
  - [x] Connector's database SHALL be used to cache and store elements
  - [x] Implement necessary APIs in API Wrapper

### Asset Catalog Management
- [x] https://github.com/sovity/edc-broker-server-extension/issues/44

### Broker UI
  - [x] Existing Asset tiles shall be used (1:1 like current Catalog Browser)
  - [x] MDS Corporate Design SHALL be followed with best-of-breed approach
    - https://mobilithek.info/offers
    - https://metaver.de/freitextsuche
    - https://catalog.test.mobility-dataspace.eu/resources
    - https://www.advaneo-datamarketplace.de/database/de/search-contents
  - [x] No mobile optimization SHALL be done

## Non-Functional Requirements

- [x] https://github.com/sovity/edc-extensions/issues/938

### edc-ui

- [x] sovity/edc-broker-server-extension#5
- [x] sovity/edc-broker-server-extension#6

### edc-broker-server-extension

- Implementation Breakdown
  - Layer "Dtos <-> DB"
    - [x] sovity/edc-broker-server-extension#22
    - [x] sovity/edc-broker-server-extension#25
    - [x] sovity/edc-broker-server-extension#26 
    - [x] sovity/edc-broker-server-extension#61
  - Layer "Update Single Connector"
    - [ ] sovity/edc-broker-server-extension#37
    - [x] sovity/edc-broker-server-extension#46
    - [x] sovity/edc-broker-server-extension#47
    - [x] sovity/edc-broker-server-extension#48
    - [x] sovity/edc-broker-server-extension#49
    - [x] sovity/edc-broker-server-extension#57
  - Layer "Scheduled Refreshes"
    - [x] sovity/edc-broker-server-extension#31
    - [x] sovity/edc-broker-server-extension#40
    - [x] sovity/edc-broker-server-extension#41
    - [x] sovity/edc-broker-server-extension#8
  - Layer "Fetch UI Data"
    - [x] sovity/edc-broker-server-extension#50
    - [x] sovity/edc-broker-server-extension#51
    - [x] sovity/edc-broker-server-extension#53
  - Moved to other milestones / not PoC vital:
    - [x] sovity/edc-broker-server-extension#11
    - [x] sovity/edc-broker-server-extension#52
    - [x] sovity/edc-extensions#937
    - [x] sovity/edc-broker-server-extension#55
    - [x] sovity/edc-broker-server-extension#59
    - [x] sovity/edc-broker-server-extension#56
    - [x] sovity/edc-broker-server-extension#54

## Acceptance Criteria
- [x] Successfully Demonstrate PoC with 1 connector being crawled (+offline/online, etc.)

## Stakeholders
@alexanderaukam @sebk46 

## Need for refinement
