### ISSUE TITLE
Release 0.0.1 PoC

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-broker-server-extension#112]
# Release

## Work Breakdown

Feel free to edit this release checklist in-progress depending on what tasks need to be done:

- [x] Release [edc-ui](https://github.com/sovity/edc-ui), this might require several steps.
- [x] Release [edc-extensions](https://github.com/sovity/edc-extensions), this might require several steps.
- [x] Decide a release version depending on major/minor/patch changes in the CHANGELOG.md.
- [x] Update this issue's title to the new version
- [x] `release-prep` PR:
  - [x] Update the CHANGELOG.md.
    - [x] Check the contents of the CHANGELOG.md and the last release, sometimes we forget to update the CHANGELOG.md.
    - [x] Add a clean `Unreleased` version.
    - [x] Add the version to the old section.
    - [x] Add the current date to the old version.
    - [x] Write or review the `Deployment Migration Notes` section.
    - [x] Ensure the `Deployment Migration Notes` section has a compatible versions table.
    - [x] Write or review a release summary.
    - [x] Remove empty sections from the patch notes.
  - [x] Update the [gradle.properties](https://github.com/sovity/edc-broker-server-extension/blob/main/gradle.properties) to contain the released edc-extensions version.
  - [x] Set the broker server release version in the [docker-compose's .env file](https://github.com/sovity/edc-broker-server-extension/blob/main/.env).
  - [x] Set the edc ui release version in the [docker-compose's .env file](https://github.com/sovity/edc-broker-server-extension/blob/main/.env).
  - [x] Merge the `release-prep` PR.
- [x] Wait for the main branch to be green.
- [x] Test the `docker-compose.yaml` with `BROKER_IMAGE=ghcr.io/sovity/broker-server-dev:main`.
- [x] Create a release and re-use the changelog section as release description, and the version as title.
- [x] Check if the pipeline built the release versions in the Actions-Section (or you won't see it).
- [x] Checkout the release tag and check test the `docker-compose.yaml`.
- [x] Check the contents of the Deployment Docs Zip from the GitHub Release.
- [x] Notify the deployment team with Deployment Docs Zip file attached to the release, which should now contain both product changes and a deployment migration guide.
- [x] `release-cleanup` PR:
    - [x] Revert the versions in the [docker-compose's .env file](.env) back to latest for the EDC UI.
    - [x] Revert the versions in the [docker-compose's .env file](.env) back to latest for the EDC CE.
    - [x] Revert the versions in the [docker-compose's .env file](.env) back to latest for the Broker Server.
    - [x] Update the [gradle.properties](https://github.com/sovity/edc-broker-server-extension/blob/main/gradle.properties) to contain the edc-extensions version `0.0.1-SNAPSHOT`.
    - [x] Revisit the changed list of tasks and compare it with [.github/ISSUE_TEMPLATE/release.md](https://github.com/sovity/edc-broker-server-extension/blob/main/.github/ISSUE_TEMPLATE/release.md). Apply changes where it makes sense.
    - [x] Merge the `release-cleanup` PR.
