### ISSUE TITLE
Validated Organization Metadata in Broker

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-broker-server-extension#131]
# Feature Request

## Description

Our connectors still have a Eclipse EDC Milestone era workaround for organization names, namely being unprotected asset properties.

Our goal is now to at least in the broker have correct organization names:

- For this we need a mapping `MDS Connector ID (=Participant ID) -> Organization Details` in the broker.
- The mapping `MDS Connector ID -> MDS ID` is trivial.
- We need the data `MDS ID -> Org Metadata` in the broker. The information will come from the Authority Portal.
- A connection `Authority Portal -> Broker(s)` already exists, so the easiest thing is to let the Authority Portal push.

## Breakdown

```[tasklist]
### Tasks
- [x] Broker Backend: API Endpoint for receiving Org Metadata
- [x] Broker Backend: DB service for Org Metadata.
- [x] Broker Backend: Enrichment of all asset metadata by "correct" metadata before delivery to the UI.
- [x] AP Backend: Pushing of Org Metadata (either periodic or on-event, periodic might be better if we don't want to persist the data in the broker, high frequency, e.g. 20s intervals should be no problem, right)
- [ ] Broker Backend: Enhance Connector API to also contain organization information.
- [ ] https://github.com/sovity/edc-broker-server-extension/issues/357
```
