### ISSUE TITLE
Use new Models + Mappers from edc-extensions

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-broker-server-extension#143]
New stuff from edc-extensions:
- [edc-extensions:utils:catalog-parser](https://github.com/sovity/edc-extensions/packages/1946497):
  - `DspCatalogService`, example usage can be seen in the `CatalogApiService` in our Connector UI API Wrapper
- [edc-extensions:utils:json-and-jsonld-utils](https://github.com/sovity/edc-extensions/packages/1946499):
  - Methods such as `JsonUtils#toJson(JsonObject)` and `JsonUtils#parseJson(String)`
- [edc-extensions:extensions:wrapper:common-api](https://github.com/sovity/edc-extensions/packages/1855598):
  - `UiAsset` that should be used in the Broker API output
  - `UiPolicy` that should be used in the Broker API output
- [edc-extensions:extensions:wrapper:common-mappers](https://github.com/sovity/edc-extensions/packages/1923635):
  - `AssetMapper` for building `UiAsset`s from Datasets, which isn't the same as an Asset JSON-LD: [CodeExample](https://github.com/sovity/edc-extensions/blob/main/extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/catalog/CatalogApiService.java#L63)
  - `PolicyMapper` for building `UiPolicy`s
  

```[tasklist]
### Tasks
- [ ] Use the new `DspCatalogService`
- [ ] Ensure our entire Broker Server API outputs `UiAsset`s only, not `AssetDto`s or something self-built
- [ ] Ensure our entire Broker Server API outputs `UiPolicy`s only, not `PolicyDto`s or something self-built
```
