### ISSUE TITLE
EDC 0 Migration in broker-server-extension

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-broker-server-extension#146]
# MvP + EDC 0.1.x
## Acceptance Criteria
- [x] Released Images of a Broker Server that use EDC 0.1.x

## Stakeholders
@alexanderaukam @sebk46 

```[tasklist]
### Tasks
- [ ] https://github.com/sovity/edc-broker-server-extension/issues/82
- [ ] https://github.com/sovity/edc-broker-server-extension/issues/257
- [ ] https://github.com/sovity/edc-broker-server-extension/issues/217
- [ ] https://github.com/sovity/edc-broker-server-extension/issues/143
- [ ] https://github.com/sovity/edc-broker-server-extension/issues/258
- [ ] https://github.com/sovity/edc-broker-server-extension/issues/308
- [ ] https://github.com/sovity/edc-broker-server-extension/issues/313
- [ ] https://github.com/sovity/edc-broker-server-extension/issues/306
```
