### ISSUE TITLE
Data Space Filter

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-broker-server-extension#16]
- [x] depends on https://github.com/sovity/edc-broker-server-extension/issues/13
- [x] There is an existing "Filter" architecture:
  - [x] Check out how each filter has a definition, where it's set with its name.
  - [x] Check out how each filter has a value getter to be used in a database query to query the available values.
  - [x] Check out how each filter has a filter application which applies selected values as a database clause.
- [x] We now want to hack in a filter "Data Space".
- [x] For this "Data Space Filter" we want to pretend some values: 
  - [x] `"Mobilithek" <=> endpoint==mobilithekEndpoint`
  - [x] `"MDS" <=> endpoint not in known data space connectors`
- [x] In general, certain connectors, in this case the Mobilithek Connector are representing entire data spaces.
- [x] There should be also the data space "MDS", which contains all other connectors.
