### ISSUE TITLE
v1.0.0 - MVP

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-broker-server-extension#2]
# MvP
### Goal

The goal is to provide a MDS Broker based on an EDC, which acts as a substitute of the previously used MDS Broker from IAIS.

## Processes
- User
  - Sort, filter and search for BrokerAssets
  - Filter for Assets of featured Connectors
  - Navigate through the BrokerAssets via pages
- System
  - Register and Unregister Connectors via custom endpoints that the broker client extension calls

## Refinement Needed
- [ ] "Simple User Documentation" from Acceptance Criteria

## Work Breakdown Structure

- [x] sovity/edc-broker-server-extension#17
- [x] https://github.com/sovity/edc-broker-server-extension/issues/122

### MVP Catalog

- [x] sovity/edc-broker-server-extension#13
- [x] sovity/edc-broker-server-extension#128 
- [x] sovity/edc-broker-server-extension#14
- [x] sovity/edc-broker-server-extension#15
- [x] sovity/edc-broker-server-extension#129 
- [x] sovity/edc-broker-server-extension#16
- [x] https://github.com/sovity/edc-broker-server-extension/issues/59

### Release

- [x] sovity/edc-broker-server-extension#121 

### Moved to MvP 1.1.0

- [x] https://github.com/sovity/edc-broker-server-extension/issues/82

### Moved to PI1

- [ ] https://github.com/sovity/edc-extensions/issues/942
- [ ] https://github.com/sovity/edc-extensions/issues/943
- [ ] https://github.com/sovity/edc-extensions/issues/937
- [ ] https://github.com/sovity/edc-extensions/issues/938
- [ ] https://github.com/sovity/edc-extensions/issues/941
- [x] https://github.com/sovity/edc-broker-server-extension/issues/52
- [x] https://github.com/sovity/edc-broker-server-extension/issues/56
- [ ] https://github.com/sovity/edc-extensions/issues/940
- [x] https://github.com/sovity/edc-broker-server-extension/issues/109

## Acceptance Criteria
- [ ] Successfully Demonstrate PoC
- [x] Image provided via GHCR
- [x] Readme with installation tutorial
- [ ] Simple User Documentation (some screenshots and how to use endpoint of asset to trasnfer data in EDC)
- [x] Docker-compose available
- [x] OpenAPI definition for APIs available
- [ ] ~~Integrated into sovity's E2E Tests~~

## Stakeholders
@alexanderaukam @sebk46 

## Need for refinement
