### ISSUE TITLE
Release 1.0.2

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-broker-server-extension#229]
```[tasklist]
### Tasks
- [ ] https://github.com/sovity/edc-broker-server-extension/pull/228
- [ ] https://github.com/sovity/edc-broker-server-extension/issues/221
- [x] `release-prep` PR:
  - [ ] Update the CHANGELOG.md.
    - [ ] Add a clean `Unreleased` version.
    - [ ] Add the version to the old section.
    - [ ] Add the current date to the old version.
    - [ ] Write or review the `Deployment Migration Notes` section.
    - [ ] Ensure the `Deployment Migration Notes` contains the compatible docker images.
    - [ ] Write or review a release summary.
    - [ ] Remove empty sections from the patch notes.
  - [ ] Update the [gradle.properties](https://github.com/sovity/edc-broker-server-extension/blob/main/gradle.properties) to contain the released edc-extensions version.
  - [ ] Set the broker server release version in the [docker-compose's .env file](https://github.com/sovity/edc-broker-server-extension/blob/main/.env).
  - [ ] Set the EDC UI release version in the [docker-compose's .env file](https://github.com/sovity/edc-broker-server-extension/blob/main/.env).
  - [ ] Set the EDC CE release version in the [docker-compose's .env file](https://github.com/sovity/edc-broker-server-extension/blob/main/.env).
  - [ ] Merge the `release-prep` PR.
- [x] Wait for the main branch to be green.
- [x] Test the `docker-compose.yaml` with `BROKER_IMAGE=ghcr.io/sovity/broker-server-dev:main`.
- [x] Create a release and re-use the changelog section as release description, and the version as title.
- [x] Check if the pipeline built the release versions in the Actions-Section (or you won't see it).
- [ ] Checkout the release tag and check test the `docker-compose.yaml`.
- [ ] Check the contents of the Deployment Docs Zip from the GitHub Release.
- [ ] Notify the deployment team with Deployment Docs Zip file attached to the release, which should now contain both product changes and a deployment migration guide.
- [ ] `release-cleanup` PR:
  - [ ] Revert the versions in the [docker-compose's .env file](.env) back to latest for the EDC UI.
  - [ ] Revert the versions in the [docker-compose's .env file](.env) back to latest for the EDC CE.
  - [ ] Revert the versions in the [docker-compose's .env file](.env) back to latest for the Broker Server.
  - [ ] Update the [gradle.properties](https://github.com/sovity/edc-broker-server-extension/blob/main/gradle.properties) to contain the edc-extensions version `0.0.1-SNAPSHOT`.
  - [ ] Revisit the changed list of tasks and compare it with [.github/ISSUE\_TEMPLATE/release.md](https://github.com/sovity/edc-broker-server-extension/blob/main/.github/ISSUE_TEMPLATE/release.md). Apply changes where it makes sense.
  - [ ] Merge the `release-cleanup` PR.
- [ ] Write message to DH with Changelog
```
