### ISSUE TITLE
"Created at" and "Contract offer id" attributes seem to be self-generated

### ISSUE THREAD

**Issue by ip312** [sovity/edc-broker-server-extension#278]
# Bug Report

## Description

I have a contract definition in my CaaS, which is visible at the test broker and which was not changed since weeks.
If I open the detail page of this offer I can see the "Contract offer Id" and "Created at" attributes.

![111](https://github.com/sovity/edc-broker-server-extension/assets/91048868/d1bc9606-1a08-45df-92a5-b9585e6e5252)

If I reload the catalog in my browser and open the detail page of the same offer, I can see another "Contract offer Id" and "Created at" attributes, although I have not changed the offer in my CaaS.

![112](https://github.com/sovity/edc-broker-server-extension/assets/91048868/602681f6-1fd1-46b3-955e-cb1e04a850c0)

And so on: both attributes seem to be self-generated in the browser.

Is that an expected behavior? I don't think so.

# Solution Proposal / Breakdown

```[tasklist]
### Tasks
- [ ] Refine the plan from https://github.com/sovity/edc-broker-server-extension/issues/278#issuecomment-1809857273 into bullet points.
- [ ] Implement the solution
- [ ] Add a test that updates a connector twice and checks that the contract offer ID did not change
```
