### ISSUE TITLE
Fix JSON-LD Handling in EDC 0 Broker

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-broker-server-extension#306]
# Bug Report

## Description

- Before Asset JSON contents were simple. String keys, String values.
- Before we could simply access the Asset Properties JSON for things such as Search, Filter Queries, accessing available Filter Values, etc. in DB Queries
- Now we have JSON-LD, which needs to be interpreted, see below..
- We'll need to add additional column(s) to the original table to be able to access data without having to semantically interpret it in the data base, since we have java code that can semantically interpret it already.

## About JSON-LD

Before the asset just looked like this: 

```json
{
   "asset:prop:id": "urn:artifact:my-id",
   "asset:prop:name": "My Asset"
}
```

Now it looks like either of these:

If the properties weren't expanded:

```json
{
   "@context": {
      "dcterms": "http://purl.org/dc/terms/"
   },
   "@id": "my-asset",
   "dcterms:title": "My Asset"
}
```

The properties should always be expanded, the values might be expanded, too:

```json
{
   "@id": "my-asset",
   "http://purl.org/dc/terms/title": "My Asset"
}
```

```json
{
   "@id": "my-asset",
   "http://purl.org/dc/terms/title": ["My Asset"]
}
```

```json
{
   "@id": "my-asset",
   "http://purl.org/dc/terms/title": {
      "@value": "My Asset"
   }
}
```

```json
{
   "@id": "my-asset",
   "http://purl.org/dc/terms/title": [{
      "@value": "My Asset"
   }]
}
```

The following is valid, and would not be affected by compaction, as you can't compact away the additional `@lang`.

```json
{
   "@id": "my-asset",
   "http://purl.org/dc/terms/title": [{
      "@value": "My Asset",
      "@lang": "EN"
   }]
}
```

## Possible Implementation and Work Breakdown

```[tasklist]
### Tasks
- [ ] Before persisting assets on updating a connector, we already extract the ID and the Name to be put into their own columns (We need the ID as pkey. We need the title to let the DB use natural sorting). We probably have to add all fields we want to access via search, filters or sorting as columns. 
- [ ] Keywords we should add already, too. However, keywords are an array.
- [ ] We should no longer access the asset properties JSON-LD in DB queries.
```
