### ISSUE TITLE
Broker UI Portal Integration

### ISSUE THREAD

**Issue by jkbquabeck** [sovity/edc-broker-server-extension#453]
# Feature Request

## Description

The Broker UI shall not be accessible to people who are not logged into the MDS Portal. When logged in, the user can access the data catalogue via the Portal menu on the left-hand side. When a portal user clicks on “data catalogue” the menu item shall show that it is currently displayed (e.g. grey background). Furthermore, the data catalogue shall have a unique link (e.g. [www.portal.mobility-dataspace.eu/datacatalogue](http://www.portal.mobility-dataspace.eu/datacatalogue)). If this link is clicked and the person is logged in, they shall be directed to the data catalogue directly. If the person is not logged in, the log in mask shall be displayed and upon successful completion, the user shall be redirected to the data catalogue and not the main page of the Portal.

The "/connectors" Page is no longer needed, since the information is available to the authority in the MDS-Portal.

This feature has to be implemented for all environments.

![Image](https://github.com/Mobility-Data-Space/MDS-Project/assets/126167440/d2f00073-76bc-4beb-8e7b-3151d87890f7)

There should be no perceivable delay/lag when a Portal user clicks on the menu item “data catalogue”.

## Which Areas Would Be Affected?

@AbdullahMuk please ccordinate if there are relevant infos to be provided here

### Problem statement

- With the introduction of the MDS Portal, the user experience of the members is drastically improved. However, the user journey is still not optimal, and several tabs are necessary to interact with all components (Portal, Broker, EDC/CaaS).

- Furthermore, the MDS needs to emphasize the value it provides to its members and create lock-in effects / increase the value of being a paying member vs. a non-paying company. The data catalogue is widely perceived as the heart of the MDS and one of the key value propositions. Currently, the data catalogue is publicly available to anybody who has the link. In conjunction with the data offers on request, the MDS sees the risk of using the data catalogue to find data offers and providers and then contact them outside of the MDS.

### Customer perspective

- Internal as well as external the user experience of the technical solution is not perceived as good. Therefore, the MDS has to prioritize features which have the biggest impact on the UX, one of those being the integration of the Portal and the Broker.

### Business value

- The MDS creates a lock-in effect once the data catalogue is not publicly available anymore and therefore increases the willingness-to-pay, which is crucial in 2024 as in 2025 membership fees are introduced.

- The overall satisfaction of the business users is improved, due to the seamless integration of the components and a better UX.

## How does this tie into the current product?

The Broker uses the same IAM as the Portal and supports the MDS SSO. Furthermore, the Broker UI (data catalogue) needs to be accessible via the Portal menu and loaded in the same tab.
The rights and roles matrix of the MDS Portal needs to be updated (all users have read access to the data catalogue).

## Scope check

_Is this feature part of the contracted scope?_
- [x] It is part of the contracted scope
- [ ] It is not part of the contracted scope

If not, please add the label "mds/future-scope"

## (For sovity Team to complete) Stakeholders

@jkbquabeck 
@alexanderaukam

## (For sovity Team to complete) Solution Proposal and Work Breakdown

```[tasklist]
- [ ] Fix the GitHub Projects Labels, Sprint and other Metadata
- [ ] Refine further action items for this feature request
```

## User stories

```[tasklist]
- [ ] As Broker UI, I want to be accessible via a menu item in the MDS-Portal UI to improve the user experience of MDS members. (https://github.com/Mobility-Data-Space/MDS-Project/issues/10)
- [ ] As Broker I want to share the same IAM and SSO as the MDS-Portal, to provide a seamless user experience and only be accessible for users of the MDS. (https://github.com/Mobility-Data-Space/MDS-Project/issues/11
- [ ] As a participant_user or higher I want to access the Broker UI via a link if I am logged in to allow bookmarking. (https://github.com/Mobility-Data-Space/MDS-Project/issues/12)
```

### Outlook

This feature is the first step to improve the user experience and offer a single touchpoint to the user (no fragmented user interfaces). This feature is a prerequisite for the offering of data without connector (RQ_0002) and permanent links for data offers (RQ_0003).

### Glossary 

Data catalogue = Name which shall be displayed in the UI for the broker.

**Comment by AbdullahMuk** [comment]
Effort Estimation added based on insights from Jakob and SO. Effort Estimation is subject to change after dev team will do the solution design and work breakdown.

**Comment by jkbquabeck** [comment]
request from MDS: please also provide an alternative solution to iFrame
