### ISSUE TITLE
Permanent Links for Data Offer

### ISSUE THREAD

**Issue by jkbquabeck** [sovity/edc-broker-server-extension#454]
# Feature Request

## Description

Each data offer (available as well as on request, see RQ_002) shall have a permanent link (e.g. [www.portal.mobility-dataspace.eu/datacatalogue/[organizationname]/[uniqueassetID]](http://www.portal.mobility-dataspace.eu/datacatalogue/organizationname/uniqueassetID,) ), which can be copied from either from the UI or from the browser address bar. This link shall contain the organization name for easy identification and a unique asset ID. 
This link shall only be accessible to users who are logged into the MDS-Portal, and if somebody opens the link and is not logged in, the login mask shall be displayed and after the successful log-in the user shall be redirected to the data offer.
If a data offer is deleted the user shall see a screen stating that the data offer is not longer available.

This feature has to be implemented for all environments.

![Image](https://github.com/Mobility-Data-Space/MDS-Project/assets/126167440/f8465c5f-2ade-4f21-877a-45b6de4f2db5)

Challenge: Link the mask which opens when you click on an asset in the data catalogue to a unique URL.

## Which Areas Would Be Affected?

_e.g., DPF, CI, build, transfer, etc._

### Problem statement

- Currently, our members have no possibility of referencing a data offer from the data catalogue. However, this feature is needed if, for example, one person wants to share an interesting data offer within the company or with another member from the community (“have a look at this offer which might be suitable for our use case”).
- Furthermore, due to the lack of this functionality, bookmarking of data offers is not possible.

### Customer perspective

- This missing feature is an impediment to efficient information sharing.
- This feature is requested by our customers to improve the workflow of using the broker and interacting within the MDS. The absence of this functionality is seen as an impediment to efficient information sharing, since you currently have to tell in which environment the other party has to look (Test/Prod) and which title has to be typed into the search bar.

### Business value

- This feature improves the usability of the data catalogue and therefore improves the user experience.
- Since our current feedback from all stakeholders is that the usability and UX of the technical solution (EDC, Broker etc.) is not user-friendly and needs to be improved this feature is requested.

## How does this tie into the current product?

This feature has a direct dependency to #453, which is a prerequisite for the implementation, due to the integration of the Broker UI into the MDS Portal and SSO

## Scope check

_Is this feature part of the contracted scope?_
- [ ] It is part of the contracted scope
- [x] It is not part of the contracted scope

If not, please add the label "mds/future-scope"

## (For sovity Team to complete) Stakeholders

_Add more on who asked for this, i.e. company, person, how much they pay us, what their tier is, are they a strategic account, etc. Who needs to be kept up-to-date about this feature?_

## (For sovity Team to complete) Solution Proposal and Work Breakdown

```[tasklist]
- [ ] Fix the GitHub Projects Labels, Sprint and other Metadata
- [ ] Refine further action items for this feature request
```

## User Stories

```[tasklist]
- [ ]  As any Portal user I want to copy a permanent link for a data offer via a button in the details mask to be able to share and reference it. (https://github.com/Mobility-Data-Space/MDS-Project/issues/13)
- [ ] As any Portal user I want to copy a permanent link for a data offer via the browser address bar when I have the details mask of an offer open. (https://github.com/Mobility-Data-Space/MDS-Project/issues/14)
- [ ] As a person who clicks on the link and is logged into the Portal, I want automatically be directed to the data offer without any further clicking needed. (https://github.com/Mobility-Data-Space/MDS-Project/issues/15)
- [ ] As a person who clicks on the link and is not logged into the Portal, I want to be redirected to the login mask and upon successful logging in, I want to automatically be redirected to the data offer. (https://github.com/Mobility-Data-Space/MDS-Project/issues/16)
- [ ] As a person who clicks on the link and is logged into the Portal, I want to see a screen stating that the data offer is no longer available, so that I am not confused if a link does not work for a data offer. (https://github.com/Mobility-Data-Space/MDS-Project/issues/35)
```

## Outlook

MDS: In the future, we also want permalinks for the data offers from a connector. If a user copies the permalink of an asset, they can copy and paste it into the catalog browser in the EDC and don't get the whole list of data offers from that connector, but that speficif data offer.

### Glossary 

Data offer link = unique permanent link for a data offer

**Comment by AbdullahMuk** [comment]
Effort Estimation added based on insights from Jakob and SO. Effort Estimation is subject to change after dev team will do the solution design and work breakdown.

**Comment by SebastianOpriel** [comment]
Important: Keep in mind that if e.g. #456 would be solved with iframe, this issue must be solved in portal, rather than in broker (maybe).
