### ISSUE TITLE
Create Broker Catalog UI

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-broker-server-extension#6]
# Epic

### Requirements
- [x] Create 1:1 copy of current catalog page and methods
- [x] Adjust visible pages
  - [x] Remove all entries in navigation bar
  - [x] Add new page "broker"
  - [x] Link to 1:1 copy above
- [x] Implement new structure
- [x] Adjust offering details
  - [x] #42
  - [x] #43

#### For MVP, not PoC
- [x] #60

#### Needs Refinement

- [ ] Create a new hidden config setting for broker (undocumented)
